heat_template_version: 2013-05-23

parameters:
  key_name:
    type: string
    default: heat_key
  flavor:
    type: string
    default: m1.tiny
  image:
    type: string
    default: cirros-0.3.4-x86_64-uec

resources:
  my_asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      resource:
        type: autoscaling_child.yaml
        properties:
          stack_id: {get_param: "OS::stack_id"}
          key_name: { get_param: key_name}
          image: { get_param: image}
          flavor: { get_param: flavor}
      min_size: 1
      max_size: 3

  scale_up_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: my_asg}
      cooldown: 60
      scaling_adjustment: 2

  scale_down_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: my_asg}
      cooldown: 60
      scaling_adjustment: '-1'

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-up if cpu load > 70 % for 1 minute
      meter_name: cpu
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 70
      alarm_actions:
        - {get_attr: [scale_up_policy, alarm_url]}
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt

  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: Scale-down if cpu load < 15 % for 1 minute
      meter_name: cpu
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 15
      alarm_actions:
        - {get_attr: [scale_down_policy, alarm_url]}
      matching_metadata: {'metadata.user_metadata.stack': {get_param: "OS::stack_id"}}
      comparison_operator: le

