heat_template_version: 2013-05-23

description: >
    HOT template demonstrates how to create configurable group of resources,
    i.e. N servers each with M volumes. Where N and M may be >= 0.

parameters:
  image:
    type: string
    default: fedora-21.x86_64
  flavor:
    type: string
    default: m1.small
  network:
    type: string
    default: private
  server_num:
    type: number
    default: 1
  volume_num:
    type: number
    default: 2
  volume_size:
    type: number
    default: 1

resources:
  servers_and_volumes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: server_num}
      resource_def:
        type: server_and_volume_group.yaml
        properties:
          volume_count: {get_param: volume_num}
          image: {get_param: image}
          flavor: {get_param: flavor}
          network: {get_param: network}
          volume_size: {get_param: volume_size}
