heat_template_version: 2013-05-23

parameters:
  server_id:
    type: string
  volume_size:
    type: number

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
      description: Volume for stack

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_param: server_id}
